import Head from 'next/head'
import Sidebar from 'components/Sidebar'
import Center from 'components/Center'
import Dashboard from 'components/Dashboard'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-gray-100 h-screen overflow-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full min-h-screen font-sans text-gray-900 bg-gray-50 flex'>
        <Sidebar /> 
        <Center />
        {/* <Dashboard /> */}


      </div>
    </div>
  )
}
